### ISSUE TITLE
Bulk upload images already in Library to Cloudinary?

### ISSUE THREAD

**Issue by jonny-harte** [joemcgill/Cloudinary-WordPress-Integration-Demo#6]
Hi,

Thanks for building this plugin and the article on css tricks. I'd like to implement this solution and customise it a bit but don't have much experience with building wordpress plugins....

Basically we already have images uploaded to the media library that I would like to send to Cloudinary. Any idea/pointers on how this could be achieved? (maybe adding a "upload to cloudinary" button to the media library assets that manually triggers the script)

**Comment by joemcgill** [comment]
Hi @hartey11 – the approach you suggest is definitely an option. Another approach you might want to look into, if this doesn't need to be a client facing feature, is building a WP CLI script that loops through all of the attachments in your media library and upload the original file to Cloudinary. You could use the same functionality for both the CLI script and as the callback on whatever admin UI you decide to add. You'd need to remember to add the Cloudinary metadata to the WordPress database using the `wp_update_attachment_metadata()` function so that this plugin knows to serve the Cloudinary assets rather than the local ones.
